version: '3.8'

services:
  # Local REVM node
  revm-node:
    image: ethereum/client-go:latest
    ports:
      - "8545:8545"
    command: 
      - --dev
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,personal

  # IPFS node
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs

  # AHIN Indexer
  ahin-indexer:
    build: ./ahin-indexer
    ports:
      - "3000:3000"
    environment:
      - RPC_URL=http://revm-node:8545
      - IPFS_URL=http://ipfs:5001
      - LEDGER_ADDRESS=${LEDGER_ADDRESS}
    depends_on:
      - revm-node
      - ipfs

  # Validator Daemon
  validator:
    build: ./validator
    environment:
      - RPC_URL=http://revm-node:8545
      - IPFS_GATEWAY=http://ipfs:8080
      - LEDGER_ADDRESS=${LEDGER_ADDRESS}
      - VALIDATOR_PRIVATE_KEY=${VALIDATOR_PRIVATE_KEY}
    depends_on:
      - revm-node
      - ipfs
      - ahin-indexer

volumes:
  ipfs-data:
